# Generated by Django 3.1.2 on 2021-02-09 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Education',
        ),
        migrations.DeleteModel(
            name='Experience',
        ),
        migrations.DeleteModel(
            name='Follows',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='Visiter',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='aboutme',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='birthDay',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='birthMonth',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='birthYear',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='company',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='connections',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='jobtitle',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='linkFacebook',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='linkGithub',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='linkInstagram',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='linkTwitter',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='linkYoutube',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='position',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='public_birth',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='public_email',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='public_phone',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='verified',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='verified_code',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='verified_with',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='views',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='website',
        ),
    ]
