# Generated by Django 3.1.2 on 2021-02-13 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20210213_0053'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='siret',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='tel_fix',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
