# Generated by Django 3.1.2 on 2021-02-13 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(default='', max_length=50, null=True)),
                ('transport', models.CharField(default='', max_length=50, null=True)),
                ('d_address', models.CharField(default='', max_length=50, null=True)),
                ('d_city', models.CharField(default='', max_length=50, null=True)),
                ('d_zipcode', models.CharField(default='', max_length=50, null=True)),
                ('d_date', models.CharField(default='', max_length=50, null=True)),
                ('e_address', models.CharField(default='', max_length=50, null=True)),
                ('e_city', models.CharField(default='', max_length=50, null=True)),
                ('e_zipcode', models.CharField(default='', max_length=50, null=True)),
                ('e_date', models.CharField(default='', max_length=50, null=True)),
                ('i1_address', models.CharField(default='', max_length=50, null=True)),
                ('i1_city', models.CharField(default='', max_length=50, null=True)),
                ('i1_zipcode', models.CharField(default='', max_length=50, null=True)),
                ('i1_date', models.CharField(default='', max_length=50, null=True)),
                ('i2_address', models.CharField(default='', max_length=50, null=True)),
                ('i2_city', models.CharField(default='', max_length=50, null=True)),
                ('i2_zipcode', models.CharField(default='', max_length=50, null=True)),
                ('i2_date', models.CharField(default='', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'contract',
            },
        ),
    ]
