# Generated by Django 3.1.2 on 2021-02-13 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='c_num',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
