# Generated by Django 3.1.2 on 2021-02-14 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0002_contract_c_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='accepted',
            field=models.CharField(default='', max_length=1, null=True),
        ),
    ]
