# Generated by Django 3.1.2 on 2021-02-16 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0003_contract_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='accepted',
            field=models.CharField(default='0', max_length=1, null=True),
        ),
    ]
