# Generated by Django 3.1.2 on 2021-02-27 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0004_auto_20210216_0629'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='cost',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
