# Generated by Django 3.1.2 on 2021-03-03 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0005_contract_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='delivery',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
