# Generated by Django 3.1.2 on 2021-02-13 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='available',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='volume',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='name',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
