# Generated by Django 3.1.2 on 2021-02-13 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20210213_0137'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='user_id',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
