# Generated by Django 3.1.2 on 2021-03-03 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_data_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(default='', max_length=50, null=True)),
                ('name', models.CharField(default='', max_length=50, null=True)),
                ('description', models.CharField(default='', max_length=255, null=True)),
                ('price', models.CharField(default='', max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'delivery',
            },
        ),
    ]
